server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  http:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
      force: true
      enabled: true
swagger:
  title: SpringBoot学习
  description: SpringBoot快速入门
  version: 1.0.0
  name: 稀客大大
  url: http://www.ipicbook.com
  email: 877058128@qq.com
mybatis-plus:
  type-aliases-package: cn.bdqn.entity
  mapper-locations: mapper/*.xml
  configuration:
    auto-mapping-behavior: full
